#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <stdexcept>
#include <string>

extern "C" {
#include <igraph.h>
#include <igraph_attributes.h>
}

#include "clique_compress_lib.cpp"
#include "op_compress_lib.cpp"
#include "bicliq_compress_lib.cpp"

namespace py = pybind11;

static igraph_t load_graph(const std::string& path) {
    igraph_t g;
    igraph_set_attribute_table(&igraph_cattribute_table);
    FILE* f = fopen(path.c_str(), "r");
    if (!f)
        throw std::runtime_error("Cannot open input file: " + path);
    int err = igraph_read_graph_graphml(&g, f, 0);
    fclose(f);
    if (err != IGRAPH_SUCCESS)
        throw std::runtime_error("Error reading GraphML: " + path);
    return g;
}

static std::vector<igraph_integer_t> compress(const std::string& path, int c_lvl, int num_proc){
    assert(c_lvl>0 && c_lvl <=3 && "c_lvl needs to be between 1 and 3");
    assert(num_proc>0 && "num_proc cannot be less than 1");

    igraph_t g = load_graph(path);
    op_compressor op_comp(g, num_proc);
    g = op_comp.compress();
    c_lvl--;
    if (c_lvl) {
        clique_compressor cliq_comp(g, num_proc);
        g = cliq_comp.compress();
        c_lvl--;
    }
    if(c_lvl){
        bicliq_compressor bicliq_comp(g, num_proc);
        g = bicliq_comp.compress();
    }
    igraph_vector_int_t edges;
    igraph_vector_int_init(&edges, 0);
    igraph_get_edgelist(&g, &edges, 0);
    std::vector<igraph_integer_t> edge_vec(VECTOR(edges), VECTOR(edges) + igraph_vector_int_size(&edges));
    igraph_vector_int_destroy(&edges);
    return edge_vec;
}



PYBIND11_MODULE(nd_compress, m) {
    m.doc() = "ND Detect graph compression bindings";


    m.def("compress", &compress,
          py::arg("input_path"), py::arg("compression_level"), py::arg("num_procs"),
          "Compress an event graph generated by ANACIN-X using the specified compression level.\n"
          "Reads input_path and return the compressed graph.");
}
